import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Typography from '../components/common/Typography';
import { useEffect } from 'react';
import axios from 'axios';
import { BASE_API } from './../api/index';
import { getCookies } from 'cookies-next';
import Header from '../components/common/Header';

const Home = () => {



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main} style={{minHeight:'100vh'}}>
          <Header/>

      </main>

    </div>
  )
}

export default Home
